name: Test Runner Self-Hosted

on: [push]

jobs:
  test:
    runs-on: self-hosted  # 🔴 Esto indica que usará tu runner privado
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Mostrar mensaje
        run: echo "✅ Workflow ejecutado en mi runner privado de Windows"
